### ISSUE TITLE
Zaprogramować działanie klasy sudoku art oraz sudoku panel (sam panel)

### ISSUE THREAD

**Issue by ghost** [Sudokunaszjestibedziezawszeteraz/Sudoku#15]

**Comment by PSwis** [comment]
blockquote {padding-left: 1ex; margin: 0px 0px 0px 0.8ex; border-left: #cccccc 1px solid;} p {margin: 0px;padding: 0px;} 
package SudokuView;import java.awt.Color;import java.awt.GridLayout;import java.util.Observable;import java.util.Observer;import javax.swing.BorderFactory;import javax.swing.JPanel;import SudokuController.SudokuController;import SudokuModel.Game;import SudokuModel.UpdateAction;public class SudokuPanel extends JPanel implements Observer {    private static final Color COLOR_CANDIDATE = new 
Color(102, 153, 255);    private Field[][] fields;       // Array of fields.    private JPanel[][] panels;      // Panels holding the fields.    public SudokuPanel() {        super(new GridLayout(3, 3));        panels = new JPanel[3][3];        for (int y = 0; y < 3; y++) {            for (int x = 0; x < 3; x++) {                panels[y][x] = new JPanel(new GridLayout(3, 3));                
panels[y][x].setBorder(BorderFactory.createLineBorder(Color.DARK_GRAY));                add(panels[y][x]);            }        }        fields = new Field[9][9];        for (int y = 0; y < 9; y++) {            for (int x = 0; x < 9; x++) {                fields[y][x] = new Field(x, y);                panels[y / 3][x / 3].add(fields[y][x]);            }        }    }    public void update(Observable o, Object arg) {        switch ((UpdateAction)arg) {            case NEW_GAME:                setGame((Game)o);                break;            case CHECK:                setGameCheck((Game)o);                break;            case SELECTED_NUMBER:            case CANDIDATES:            case HELP:                setCandidates((Game)o);                break;        }    }    public void setGame(Game game) {        for (int 
y = 0; y < 9; y++) {            for (int x = 0; x < 9; x++) {                fields[y][x].setBackground(Color.WHITE);                fields[y][x].setNumber(game.getNumber(x, y), false);            }        }    }    private void setGameCheck(Game game) {        for (int y = 0; y < 9; y++) {            for (int x = 0; x < 9; x++) {                fields[y][x].setBackground(Color.WHITE);                if (fields[y][x].getForeground().equals(Color.BLUE))                    fields[y][x].setBackground(game.isCheckValid(x, y) ? Color.GREEN : Color.RED);            }        }    }    private void setCandidates(Game game) {        for (int y = 0; y < 9; y++) {            for (int x = 0; x < 9; x++) {                fields[y][x].setBackground(Color.WHITE);                if 
(game.isHelp() && game.isSelectedNumberCandidate(x, y))                    fields[y][x].setBackground(COLOR_CANDIDATE);            }        }    }    public void setController(SudokuController sudokuController) {        for (int y = 0; y < 3; y++) {            for (int x = 0; x < 3; x++)                panels[y][x].addMouseListener(sudokuController);        }    }}
 
SudokuPanel() – Graficzne generowanie pola gry
 
update(Observable o, Object arg) – Kontrola gry
 
setGame(Game game) – Ustawianie koloru t�a pól oraz wpisywanie liczb
 
setGameCheck(Game game) – Obs�uga zmiany koloru t�a pól podczas sprawdzania
 
setCandidates(Game game) – Obs�uga zmiany koloru t�a pól przy u�ywaniu pomocy
 
setController(SudokuController sudokuController) – Interfejs s�uchacza myszy

**Comment by PSwis** [comment]
package SudokuView;

import java.awt.Color;
import java.awt.GridLayout;
import java.util.Observable;
import java.util.Observer;
import javax.swing.BorderFactory;
import javax.swing.JPanel;
import SudokuController.SudokuController;
import SudokuModel.Game;
import SudokuModel.UpdateAction;

public class SudokuPanel extends JPanel implements Observer {
    private static final Color COLOR_CANDIDATE = new Color(102, 153, 255);

```
private Field[][] fields;       // Array of fields.
private JPanel[][] panels;      // Panels holding the fields.

public SudokuPanel() {
    super(new GridLayout(3, 3));

    panels = new JPanel[3][3];
    for (int y = 0; y < 3; y++) {
        for (int x = 0; x < 3; x++) {
            panels[y][x] = new JPanel(new GridLayout(3, 3));
            panels[y][x].setBorder(BorderFactory.createLineBorder(Color.DARK_GRAY));
            add(panels[y][x]);
        }
    }

    fields = new Field[9][9];
    for (int y = 0; y < 9; y++) {
        for (int x = 0; x < 9; x++) {
            fields[y][x] = new Field(x, y);
            panels[y / 3][x / 3].add(fields[y][x]);
        }
    }
}

public void update(Observable o, Object arg) {
    switch ((UpdateAction)arg) {
        case NEW_GAME:
            setGame((Game)o);
            break;
        case CHECK:
            setGameCheck((Game)o);
            break;
        case SELECTED_NUMBER:
        case CANDIDATES:
        case HELP:
            setCandidates((Game)o);
            break;
    }
}

public void setGame(Game game) {
    for (int y = 0; y < 9; y++) {
        for (int x = 0; x < 9; x++) {
            fields[y][x].setBackground(Color.WHITE);
            fields[y][x].setNumber(game.getNumber(x, y), false);
        }
    }
}

private void setGameCheck(Game game) {
    for (int y = 0; y < 9; y++) {
        for (int x = 0; x < 9; x++) {
            fields[y][x].setBackground(Color.WHITE);
            if (fields[y][x].getForeground().equals(Color.BLUE))
                fields[y][x].setBackground(game.isCheckValid(x, y) ? Color.GREEN : Color.RED);
        }
    }
}

private void setCandidates(Game game) {
    for (int y = 0; y < 9; y++) {
        for (int x = 0; x < 9; x++) {
            fields[y][x].setBackground(Color.WHITE);
            if (game.isHelp() && game.isSelectedNumberCandidate(x, y))
                fields[y][x].setBackground(COLOR_CANDIDATE);
        }
    }
}

public void setController(SudokuController sudokuController) {
    for (int y = 0; y < 3; y++) {
        for (int x = 0; x < 3; x++)
            panels[y][x].addMouseListener(sudokuController);
    }
}
```

}

Klasa SudokuPanel:

SudokuPanel() – Graficzne generowanie pola gry
update(Observable o, Object arg) – Kontrola gry
setGame(Game game) – Ustawianie koloru tła pól oraz wpisywanie liczb
setGameCheck(Game game) – Obsługa zmiany koloru tła pól podczas sprawdzania
setCandidates(Game game) – Obsługa zmiany koloru tła pól przy używaniu pomocy
setController(SudokuController sudokuController) – Interfejs słuchacza myszy
