### ISSUE TITLE
!!PILNE!!  Dokument detaliczny!!

### ISSUE THREAD

**Issue by ghost** [Sudokunaszjestibedziezawszeteraz/Sudoku#28]
Specyfikacja klas i metod (w dokumencie detalicznym), proszę to zrobić najszybciej jak to jest możliwe

**Comment by ghost** [comment]
Dodałem plik 'Specyfikacja klas.docx' do folderu 'Dokumentacja'

**Comment by potoniecj** [comment]
uaktualniłem Sudoku - Dokument Detaliczny - vI.docx o specyfikiacje klas, aktualnie mam problem z przekonwertowaniem tego do pdf bo przesuwa sie, jak ktos moze to niech sproboje i doda pdf o nazwie Sudoku - Dokument Detaliczny - vII

**Comment by potoniecj** [comment]
ok wysłano, mam nadzieję że poprawnie się wyświetla
